import { Metadata } from 'next';
import Link from 'next/link';
import { ArrowLeft, Shield } from 'lucide-react';

export const metadata: Metadata = {
  title: 'Terms of Service | SwiftMX Bridge',
  description: 'Terms of service and liability limitations for the SwiftMX Bridge conversion platform.',
};

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-gray-50 pb-20">
      <header className="bg-white border-b border-gray-200">
        <nav className="container mx-auto px-4 h-16 flex items-center">
          <Link href="/" className="flex items-center space-x-2 text-gray-500 hover:text-gray-900 transition-colors">
            <ArrowLeft className="w-4 h-4" />
            <span className="font-medium text-sm">Back to Home</span>
          </Link>
        </nav>
      </header>

      <main className="container mx-auto px-4 py-16 max-w-4xl">
        <div className="bg-white p-8 md:p-12 rounded-2xl shadow-sm border border-gray-100">
          <div className="flex items-center space-x-4 mb-8">
            <div className="w-12 h-12 bg-blue-100 rounded-xl flex items-center justify-center">
              <Shield className="w-6 h-6 text-blue-600" />
            </div>
            <h1 className="text-3xl md:text-4xl font-bold text-gray-900">Terms of Service</h1>
          </div>
          
          <div className="prose prose-blue max-w-none text-gray-600">
            <p className="text-sm font-medium text-gray-500">Last Updated: {new Date().toLocaleDateString()}</p>
            
            <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4">1. Acceptance of Terms</h2>
            <p>
              By accessing and using SwiftMX Bridge ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.
            </p>

            <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4">2. Description of Service</h2>
            <p>
              SwiftMX Bridge provides software tools to assist in the translation, parsing, and validation of financial messages (including SWIFT MT and ISO 20022 MX formats). The Service is intended to act as a technical utility to aid developers and financial institutions.
            </p>

            <h2 className="text-xl font-bold text-red-600 mt-8 mb-4">3. Limitation of Liability and "As-Is" Disclaimer</h2>
            <div className="bg-red-50 p-6 rounded-xl border border-red-100 my-6">
              <p className="text-red-800 font-medium m-0">
                THE SERVICE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
              </p>
              <p className="text-red-800 mt-4 mb-0">
                IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
              </p>
            </div>
            <p>
              SwiftMX Bridge is a translation tool, not a financial advisor, clearing house, or network operator. We do not guarantee that the output generated by the Service will be accepted by the SWIFT network, domestic clearing systems, or any beneficiary institution. 
            </p>
            <p>
              <strong>User Responsibility:</strong> You are strictly and solely responsible for verifying the accuracy, compliance, and validity of any financial message before transmitting it to a live network or using it to execute actual financial transfers. SwiftMX Bridge shall not be liable for any direct, indirect, incidental, special, or consequential damages resulting from delayed payments, network rejections (NACKs), compliance violations, or any financial loss whatsoever.
            </p>

            <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4">4. Acceptable Use</h2>
            <p>
              You agree not to use the Service for any unlawful purpose or in any way that could damage, disable, overburden, or impair the Service. You agree not to attempt to gain unauthorized access to any part of the Service or its related systems or networks.
            </p>

            <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4">5. Intellectual Property</h2>
            <p>
              The Service and its original content, features, and functionality are owned by SwiftMX Bridge and are protected by international copyright, trademark, patent, trade secret, and other intellectual property or proprietary rights laws.
            </p>

            <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4">6. Changes to Terms</h2>
            <p>
              We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide notice of any significant changes.
            </p>

            <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4">7. Contact Information</h2>
            <p>
              If you have any questions about these Terms, please contact us through the Contact page in your dashboard.
            </p>
          </div>
        </div>
      </main>
    </div>
  );
}
